defaults: &defaults
  working_directory: ~/github-bot-ui
  docker:
    - image: circleci/node:8.4.0

tag-filter: &tag-filter
  tags:
    only: /[0-9]+(\.[0-9]+){2,}/

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: make all
      - persist_to_workspace:
          root: .
          paths:
            - build
  publish:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/github-bot-ui
      - run: |
          echo -e "${NPM_USER}\n${NPM_PASSWORD}\n${NPM_EMAIL}" | npm login
          npm publish build

workflows:
  version: 2
  default:
    jobs:
      - build:
          filters:
            <<: *tag-filter
      - publish:
          requires:
            - build
          filters:
            <<: *tag-filter
            branches:
              ignore: /.*/
